Create API Endpoint for Retrieving Leaderboard Data #80
DSC-McMaster-U/Gamified-Learning-Platform pull request #104
Opened 2024-02-11 22:53 UTC by racheldennis

#### Changes Made:
- Created a new route in the Flask app to handle GET requests for retrieving leaderboard data.
- Implemented logic to fetch and return a sorted list of users based on leaderboard criteria.
- Implemented pagination in the response to handle many users efficiently.

#### Details:
- Added a new route `'/leaderboard'` in `app.py` to handle GET requests for leaderboard data.
- Implemented sorting logic to retrieve users based on specific criteria (e.g., score) in `app.py`.
- Implemented pagination logic to efficiently handle large datasets in the response.
- Modified `dashboard.html` to display leaderboard data fetched from the API endpoint.
- Ensured the leaderboard was correctly displayed with pagination controls and relevant user information.

#### Testing:
- Having difficulty testing the `dashboard.html` to see if API is incorporated correctly due to difficulties with running Flask

#### Notes:
- Please review and provide feedback on the implementation of the new leaderboard API endpoint and its integration with the dashboard.
- Also, review if the pagination mechanism is working as expected and can efficiently handle a large number of users.
- Any suggestions for further improvements or enhancements are welcome.
- Shows there are other changes to files. This is only due to syncing files to my current repository.

2024-02-11 23:31 UTC, zareentk commented on app/src/app.py
> +        return render_template('dashboard.html')
Could potentially cause issues Sude’s dashboard can only open up if logged in

2024-02-16 09:36 UTC, MithunPara requested changes
The PR looks good! As part of my previous issue, I wasn't aware that you were working on a similar issue as I also implemented an API endpoint to fetch new leaderboard data that was merged in earlier in the week, which shares many of the same features. There are a couple things I noticed in your code that could improve the endpoint I set up. I just wanted to get your thoughts on some of the differences between our code before we set up the finalized endpoint moving forward, which is why I left the PR status on Request changes for now. I left a couple notes on the PR to point out things we might want to keep in mind for the future and also left a few potential minor changes. Once the endpoint is set up, we should also consider testing the code with Sky's new PR for the leaderboard frontend page as there could be some new issues that arise.

2024-02-16 09:36 UTC, MithunPara commented on app/src/app.py
> +        return User.query.order_by(User.score.desc()).all()
I like the idea to separate the sorting logic into a different method. In my implementation, I had the rankings ordered by points for now, we could potentially use XP (XP that contributes to user level) too, but we would have to edit the model so there is some attribute that stores total XP earned throughout the user's account lifetime or track recent XP earned. Alex brought up the idea that points can be decreased as well based on factors like user performance so it might be better to take that approach.

2024-02-16 09:36 UTC, MithunPara commented on app/src/app.py
> +
We should add this section below, in my set up, I forgot to consider that we should be returning the appropriate users to display next.

2024-02-16 09:36 UTC, MithunPara commented on app/src/app.py
> +        paginated_data = leaderboard_data[start_index:end_index]
Could this potentially return an error on the last set of users to display on the leaderboard if the end_index is set beyond the total number of users?

2024-02-16 09:36 UTC, MithunPara commented on app/src/app.py
> +    @app.route('/leaderboard', methods=['GET'])
We can move the API endpoint to the routes.py file as this is where the other JSON responses are being stored.

2024-02-16 09:36 UTC, MithunPara commented on app/src/app.py
> +        return User.query.order_by(User.score.desc()).all()
We can maybe use the paginate feature part of SQLAlchemy, in the query here to return the specific page or set of users we need, this might help to optimize the query performance instead of querying all the users (which could be slow for large number of users).

2024-02-16 09:36 UTC, MithunPara commented on app/src/app.py
> +                    'rank': i + 1,
I think we should switch the rank calculation to start_index + i + 1, as the loop here is indexing from 0, which might lead to the wrong rank shown for users after the first page.

2024-02-16 09:36 UTC, MithunPara commented on app/src/templates/dashboard.html
> +                        {% for user in leaderboard_data %}
Looks good, just wanted to note that the dashboard route should limit the query for leaderboard_data to the top 5 users if we haven't set that up yet.

2024-02-16 09:36 UTC, MithunPara commented on app/src/templates/dashboard.html
> +                            <span class="leaderboard-points">{{ user.points }} XP</span>
Switch to user.points.points to correctly access the user points value from the points model.

2024-03-17 23:07 UTC, MithunPara approved these changes

2024-03-17 23:07 UTC, merged