added contact page
DSC-McMaster-U/Gamified-Learning-Platform pull request #139
Opened 2024-03-11 18:57 UTC by skydonline

# Changes made:
- Created a contact/help page
  - Users can email GDSC directly
  - There is an FAQ section with 3 current FAQs, but there can easily be added more in the JS section

2024-03-13 00:17 UTC, skydonline commented
Primary Reviewer: @angadk4

2024-03-13 00:36 UTC, alexchen2 requested changes
In terms of functionality, the page looks good to me. I just made a couple of styling suggestions regarding spacing and text alignment, but the PR should be ready to merge afterwards.

2024-03-13 00:36 UTC, alexchen2 commented on app/src/static/css/contact.css
> +    display: flex;
Change this to `display: inline` for properly-centered text, since the heading remains left-aligned on large device screens

2024-03-13 00:36 UTC, alexchen2 commented on app/src/static/css/contact.css
> +    font-weight: 500;
Add `margin-bottom: 40px` for better spacing between the subheading and button

2024-03-13 00:36 UTC, alexchen2 commented on app/src/static/css/contact.css
> +    margin-top: 10px;
Increase the top margin to 40px for better spacing between sections

2024-03-13 00:36 UTC, alexchen2 commented on app/src/static/css/contact.css
> +    margin-top: 25px;
Increase this to 60px for consistency with other pages (in terms of spacing between header and page content)

2024-03-13 00:36 UTC, alexchen2 commented on app/src/static/css/contact.css
> +    transition: var(--btn-transition);
This and its respective CSS variable at line 16 are redundant, since the button never actually changes appearance between different states; if you intended it to do so, I'd add some sort of additional hover/active/focus/etc. attribute to the button that alters the button in some way (otherwise this can just be removed).

2024-03-17 23:08 UTC, skydonline reviewed
Fixed requested changes! @alexchen2

2024-03-17 23:33 UTC, alexchen2 approved these changes

2024-03-18 01:13 UTC, merged