login unit test, refactored app.py
DSC-McMaster-U/Gamified-Learning-Platform pull request #28
Opened 2023-10-27 23:46 UTC by clarawong20

created unit testing for the login function. checks for the following:

- login page is accessible
- login with valid user credentials
- login with invalid credentials

also refactored app.py so that it would create and configure the app for testing purposes

2023-10-30 01:07 UTC, zareentk requested changes

2023-10-30 01:07 UTC, zareentk commented on app/src/app.py
>  from models import db, User
There seems to be two db's, one could potentially be removed

2023-10-30 01:07 UTC, zareentk commented on tests/test_login.py
> +        self.assertEqual(response.status_code, 200)
A few more assertions could be helpful in testing

2023-11-01 23:56 UTC, skydonline requested changes
Please update the import, check the comment. Only need to update to `.models`

2023-11-01 23:56 UTC, skydonline commented on app/src/app.py
>  from models import db, User
Relative imports, from local files from within the project, need to have a `.` infront of them. So it should be `.models`. External packages, like `flask`, do not need to have a `.` infront of them.

2023-11-02 14:10 UTC, skydonline approved these changes

2023-11-02 17:12 UTC, skydonline approved these changes

2023-11-06 01:27 UTC, zareentk approved these changes
Looks great!

2023-11-06 01:29 UTC, merged