Added testing for registration, added register form fields, fixed IntregityError for register
DSC-McMaster-U/Gamified-Learning-Platform pull request #39
Opened 2023-11-03 14:13 UTC by skydonline

**Changes made:**
- Created `test_registration.py`, which tests the register endpoint.
  - Tests for a successful redirect (status code 302) and getting a successful response (status code 200) back. This was made for in the case of proper inputs in the register fields, as well as improper inputs (e.g. not matching passwords)
- Added additional fields to the `/register` endpoint, to ensure all the data is collected.
- Fixed #37 `IntegrityError` by modifying the user model.
  - Added a "Not Available" option to `GradeEnum`, which will be the default field in the case that the user registers without inputting a grade.

**Things to note:**
- Will modify `/register` logic in the future, to correctly input data if it is provided (like create the user model with a date of birth if it is given, otherwise leave it `Null`)

2023-11-05 06:43 UTC, MithunPara commented on tests/test_registration.py
> +    response1 = client.post('/register', data={
I think some general comments explaining each client request could be helpful just for clarification

2023-11-05 07:13 UTC, MithunPara requested changes

2023-11-05 07:13 UTC, MithunPara commented on tests/test_registration.py
> +    response1 = client.post('/register', data={
I think some general comments explaining each client request could be helpful just for clarification

2023-11-05 07:13 UTC, MithunPara commented on tests/test_registration.py
> +    assert response2.location == '/register'
I believe that the location field for a response provides the full URL (could be mistaken). 
Using the lines below could parse the URL for the path:
from urllib.parse import urlparse
parsed_location = urlparse(response2.location)
assert parsed_location.path == '/register'

2023-11-05 07:13 UTC, MithunPara commented on tests/test_registration.py
> +    response4 = client.delete('/register', data={
Liked these assertions checking requests that should not be allowed for registration.

2023-11-05 07:13 UTC, MithunPara commented on tests/test_registration.py
> +@pytest.fixture
Could add a temporary database in the fixture or just make sure to clear all the entries in the existing database after testing, to check whether a registered user is successfully stored in the database  (Lines that could be added to initialize database below):
with app.test_client() as client:
            with app.app_context():
                        db.create_all()
                        yield client
                       db.drop_all()

2023-11-05 07:13 UTC, MithunPara commented on tests/test_registration.py
> +def test_register(client):
Maybe add some extra assertions just for edge cases like an empty username.

2023-11-05 14:15 UTC, skydonline commented on tests/test_registration.py
> +    assert response2.location == '/register'
This checks the relative URL, not the full URL (i.e. http://127.0.0.1:5000/register = "/register")

2023-11-05 20:15 UTC, racheldennis approved these changes

2023-11-06 21:18 UTC, MithunPara approved these changes

2023-11-06 21:19 UTC, merged