Added logic to fetch data and updates to the dashboard
DSC-McMaster-U/Gamified-Learning-Platform pull request #60
Opened 2023-11-12 20:32 UTC by skydonline

### Changes made:
- Created `routes.py` This will serve as the file for all AJAX requests to update the frontend of the application
- Added a `points` and `streak` column to the user model. This keeps track of the current daily streak and the amount of points the user has.
- Implemented logic for the dashboard to update the streak and points section upon page load and every 10 seconds. The basic format to set up a AJAX request to the backend is the following:
```
function FUNCTION_NAME() {
         $.ajax({
             url: ROUTE_URL,
             method: "GET",
             success: function (data) {
                 // DO SOMETHING
             },
             error: function (error) {
                 console.error("Error fetching user stats:", error);
             },
         });
     }
```
  - `FUNCTION_NAME` is what you decide to name the function. `ROUTE_URL` is the name of the route in the `routes.py` file. It should be the same as the `ROUTE_URL` in `@routes.route(ROUTE_URL, methods=['GET'])`. Inside the `success` block, run the necessary code to render the data.

2023-11-15 00:10 UTC, zareentk commented
Hi Sky remember to ask for a reviewer next time, but I can review this one for now

2023-11-15 00:19 UTC, zareentk requested changes
There doesn’t seem to be any major issues from a first pass, but just fix the setInterval time and I’ll approve it!

2023-11-15 00:19 UTC, zareentk commented on app/src/models.py
> +    points = db.Column(db.Integer, default=0)
As previously discussed in the meeting Clara’s model can be used for this, so incorporate it if you have availability

2023-11-15 00:19 UTC, zareentk commented on app/src/templates/user_profile.html
> +        setInterval(userStats, 10000);
This could cause an issue when we eventually migrate to cloud, so try to change this to 30s or even 1 minute

2023-11-15 14:10 UTC, skydonline commented
I fixed a few issues that prevented the application from working after merging in Clara's and Alex's PRs. There was an issue in the Quiz model ForeignKey reference, `nullable=False` shouldn't be in that reference. Additionally, Flask doesn't allow multiple script blocks to be in the same `.html` file, so I just combined Alex's and my JavaScript code into the same block. I also updated the time to fetch user stats from the database.

2023-11-16 01:02 UTC, zareentk commented
Sounds good, the changes fix all the necessary issues so it’s good to go!

2023-11-16 01:02 UTC, zareentk approved these changes

2023-11-16 03:30 UTC, merged